def initialize():
    global num1 #Passtimes
    num1 = 0
    global num2 #Fialtimes
    num2 = 0
    global num3 #Interrupt
    num3 = 0
    global num4 #LinkDown
    num4 = 0
    global num5 #FailList1
    num5 = 0
    global num6 #FailList2
    num6 = 0
    global str1 #filename
    str1 = ""
    global str2 #IXIAport
    str2 = ""
    global str3 #FailList1
    str3 = ""
    global str4 #FailList2
    str4 = ""
    global str5 #Mode
    str5 = ""
def counter():
    global num1 #Passtimes
    num1 = 0
    global num2 #Fialtimes
    num2 = 0
    global num4 #LinkDown
    num4 = 0
    global num5 #FailList1
    num5 = 0
    global num6 #FailList2
    num6 = 0
    global str3 #FailList1
    str3 = ""
    global str4 #FailList2
    str4 = ""